# The URL the site will be built for
base_url = "https://estenssorog.com"
title = "estenssorog"
theme = "apollo"

# generate_feed = true
# feed_filename = "rss.xml"

compile_sass = true
build_search_index = false

taxonomies = [
    { name = "tags"},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]
toc = false
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
#    { name = "/projects", url = "/projects", weight = 3 },    
]

socials = [
    { name = "github", url = "https://github.com/gavinest", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/gavinest/", icon = "linkedin" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
]

custom_css = []